In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
from pandas_datareader import data as pdr
import matplotlib.pyplot as plt
import seaborn as sns

yf.pdr_override()

In [2]:
ticker_df = pd.read_csv("2023-07-15-WatchListScanner.csv")
ticker_df

,Symbol,Description,Last,Net Chng,%Change,volumechange,Volume,Bid,Return on Equity (ROE) - Current (Annual),Ask,High,Low,Market Cap
0,FUN,CEDAR FAIR LP DEPOSITRY UTS(REP LTD PART),37.50,-0.25,-0.66%,-16.60,"533,110",37.14,1535.5000,37.86,37.730,37.300,"1,925 M"
1,TNL,TRAVEL PLUS LEISURE CO COM,41.82,-1.32,-3.06%,62.36,"818,279",41.40,689.2300,42.24,43.170,41.430,"3,188 M"
2,RRR,RED ROCK RESORTS INC COM CL A,49.07,0.39,+0.80%,-25.26,"275,451",48.53,397.8700,49.60,49.070,48.070,"2,856 M"
3,TPX,TEMPUR SEALY INTERNATIONAL INC COM,43.97,-0.02,-0.05%,-11.95,"1,334,089",43.54,345.6200,44.39,44.130,43.390,"7,566 M"
4,FTDR,FRONTDOOR INC COM,34.04,-0.07,-0.21%,-57.45,"391,285",33.80,225.4000,34.28,34.180,33.760,"2,782 M"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,TX,TERNIUM SA ADR,43.79,0.07,+0.16%,26.53,"223,717",43.55,15.7950,44.05,43.890,43.125,"8,596 M"
196,OFG,OFG BANCORP COM,28.26,-0.15,-0.53%,-9.84,"195,549",27.35,15.7460,29.87,28.695,28.140,"1,343 M"
197,DOCS,DOXIMITY INC COM CL A,35.35,0.22,+0.63%,-58.91,"1,038,728",34.51,12.2320,38.90,35.490,34.755,"6,885 M"
198,SWBI,SMITH AND WESSON BRANDS INC COM,13.15,-0.18,-1.35%,-0.19,"287,903",13.00,9.8978,13.15,13.330,12.990,606 M
199,CDMO,AVID BIOSERVICES INC COM,13.23,-0.14,-1.05%,18.70,"402,040",12.57,0.3077,13.93,13.520,13.125,830 M

In [4]:
tickers = ticker_df['Symbol']

In [4]:
# fmp_key = "806b1540043a45c09f1a2f97d9a1d6e4"
# companies = Toolkit(list(ticker_df['Symbol']), api_key=fmp_key)

In [5]:
# companies.ratios

In [6]:
# historical_data = companies.get_historical_data(start="2018-01-01", end="2021-01-01")

In [7]:
# historical_data

In [8]:
# companies.ratios.collect_profitability_ratios()

In [6]:
df = pdr.DataReader(list(tickers), start="2022-01-01", end="2023-01-01", period='1d')

Failed to get ticker 'CWEN/A' reason: Expecting value: line 1 column 1 (char 0)

[*********************100%***********************]  200 of 200 completed

4 Failed downloads:
['CWEN/A']: Exception('%ticker%: No timezone found, symbol may be delisted')
['NXT', 'AESI', 'VTS']: Exception("%ticker%: Data doesn't exist for startDate = 1577854800, endDate = 1672462800")

In [7]:
df

           Adj Close                                                   \
                ACEL        ACT       AEHR AESI       AIRC       AMBC
Date
2020-01-02     12.50        NaN   2.070000  NaN        NaN  21.760000
2020-01-03     12.57        NaN   2.090000  NaN        NaN  21.730000
2020-01-06     12.40        NaN   1.980000  NaN        NaN  21.760000
2020-01-07     12.24        NaN   1.940000  NaN        NaN  21.400000
2020-01-08     12.11        NaN   2.010000  NaN        NaN  21.540001
...              ...        ...        ...  ...        ...        ...
2022-12-23      7.57  23.894825  20.980000  NaN  33.550362  16.650000
2022-12-27      7.53  23.825680  20.219999  NaN  33.442986  16.750000
2022-12-28      7.41  23.341656  19.900000  NaN  32.867058  16.700001
2022-12-29      7.61  23.726898  20.629999  NaN  33.560127  17.139999
2022-12-30      7.70  23.825680  20.100000  NaN  33.491798  17.440001

                                                  ...   Volume           \
                 AMKR       APAM      ARCO  ARHS  ...      WAL      WEN
Date                                              ...
2020-01-02  12.926229  23.766167  7.771887   NaN  ...   499400  2359700
2020-01-03  12.575293  23.744238  7.590924   NaN  ...   586300  1660100
2020-01-06  12.526550  23.883135  7.762362   NaN  ...  1024600  2329500
2020-01-07  12.702019  24.131689  7.705217   NaN  ...   476300  2376300
2020-01-08  12.721518  24.182861  7.619496   NaN  ...   731100  2155500
...               ...        ...       ...   ...  ...      ...      ...
2022-12-23  24.356848  29.580568  8.221309  9.24  ...   801100   955100
2022-12-27  24.257435  29.369347  8.043445  9.44  ...  1119900  1165500
2022-12-28  23.442225  28.284435  8.102733  9.50  ...   540500  1016400
2022-12-29  23.869713  28.802889  8.250954  9.75  ...   555200  1384600
2022-12-30  23.839886  28.514862  8.260834  9.75  ...   466300  1231200

                                                                           \
              WERN     WHD     WNC      WSC         X     YETI        ZIM
Date
2020-01-02  437700  444900  461700   319100  18748300  1529200        NaN
2020-01-03  399000  282800  365700   212000  10491200  1371900        NaN
2020-01-06  413800  267900  289500   259400   9685400  3290600        NaN
2020-01-07  375700  207500  279200   268600  11908800  1736900        NaN
2020-01-08  374000  413500  232600   188900   9925100  1759400        NaN
...            ...     ...     ...      ...       ...      ...        ...
2022-12-23  292400  258400  251200   984700   4165900   505300  1936100.0
2022-12-27  297400  202400  484600   710000   3603000   571200  2897500.0
2022-12-28  254600  342800  418600  1001800   4669100   776200  2890200.0
2022-12-29  302100  195100  344600   864000   4591800   885700  4549900.0
2022-12-30  389700  216300  415400  1267000   3603100   539200  4140200.0


                 ZIP
Date
2020-01-02       NaN
2020-01-03       NaN
2020-01-06       NaN
2020-01-07       NaN
2020-01-08       NaN
...              ...
2022-12-23  354600.0
2022-12-27  347600.0
2022-12-28  371000.0
2022-12-29  398900.0
2022-12-30  404800.0

[756 rows x 1200 columns]