In [1]:
from financetoolkit import Toolkit

In [2]:
fmp_key = "806b1540043a45c09f1a2f97d9a1d6e4"
companies = Toolkit(['AAPL', 'MSFT'], api_key=fmp_key)

In [3]:
companies.get_enterprise()

           Stock Price  Number of Shares  Market Capitalization  \
     date
AAPL 1985     0.070313       13708800000           9.639069e+08
     1986     0.149550       14373333333           2.149532e+09
     1987     0.504460       14674698795           7.402799e+09
     1988     0.386160       14556363636           5.621085e+09
     1989     0.397320       14363841808           5.707042e+09
...                ...               ...                    ...
MSFT 2018    98.610000        7700000000           7.592970e+11
     2019   135.680000        7673000000           1.041073e+12
     2020   203.510000        7610000000           1.548711e+12
     2021   270.900000        7547000000           2.044482e+12
     2022   256.830000        7496000000           1.925198e+12

           Cash and Cash Equivalents   Total Debt  Enterprise Value
     date
AAPL 1985                  337000000            0         626906854
     1986                  576200000            0        1573331999
     1987                  565100000            0        6837698554
     1988                  545700000    127900000        5203285381
     1989                  438300000     56800000        5325541627
...                              ...          ...               ...
MSFT 2018                11946000000  81808000000      829159000000
     2019                11356000000  78366000000     1108082640000
     2020                13576000000  70998000000     1606133100000
     2021                14224000000  67775000000     2098033299999
     2022                13931000000  61270000000     1972536680000

[76 rows x 6 columns]

In [4]:
historical_data = companies.get_historical_data(start="2018-01-01", end="2021-01-01")

In [5]:
historical_data

             Adj Close                   Close                    High  \
                  AAPL        MSFT        AAPL        MSFT        AAPL
Date
2018-01-02   40.831604   80.562042   43.064999   85.949997   43.075001
2018-01-03   40.824478   80.936981   43.057499   86.349998   43.637501
2018-01-04   41.014099   81.649330   43.257500   87.110001   43.367500
2018-01-05   41.481068   82.661629   43.750000   88.190002   43.842499
2018-01-08   41.326988   82.745995   43.587502   88.279999   43.902500
...                ...         ...         ...         ...         ...
2020-12-24  130.025940  217.824768  131.970001  222.750000  133.460007
2020-12-28  134.676422  219.985901  136.690002  224.960007  137.339996
2020-12-29  132.883209  219.193832  134.869995  224.149994  138.789993
2020-12-30  131.750153  216.778442  133.720001  221.679993  135.990005
2020-12-31  130.735352  217.502075  132.690002  222.419998  134.740005

                               Low                    Open              \
                  MSFT        AAPL        MSFT        AAPL        MSFT
Date
2018-01-02   86.309998   42.314999   85.500000   42.540001   86.129997
2018-01-03   86.510002   42.990002   85.970001   43.132500   86.059998
2018-01-04   87.660004   43.020000   86.570000   43.134998   86.589996
2018-01-05   88.410004   43.262501   87.430000   43.360001   87.660004
2018-01-08   88.580002   43.482498   87.599998   43.587502   88.199997
...                ...         ...         ...         ...         ...
2020-12-24  223.610001  131.100006  221.199997  131.320007  221.419998
2020-12-28  226.029999  133.509995  223.020004  133.990005  224.449997
2020-12-29  227.179993  134.339996  223.580002  138.050003  226.309998
2020-12-30  225.630005  133.399994  221.470001  135.580002  225.229996
2020-12-31  223.000000  131.720001  219.679993  134.080002  221.699997

               Volume
                 AAPL      MSFT
Date
2018-01-02  102223600  22483800
2018-01-03  118071600  26061400
2018-01-04   89738400  21912000
2018-01-05   94640000  23407100
2018-01-08   82271200  22113000
...               ...       ...
2020-12-24   54930100  10550600
2020-12-28  124486200  17933500
2020-12-29  121047300  17403200
2020-12-30   96452100  20272300
2020-12-31   99116600  20942100

[756 rows x 12 columns]

In [7]:
companies.ratios.collect_profitability_ratios()

date                                                   2018       2019  \
AAPL Gross Margin                                  0.383437   0.378178
     Operating Margin                               0.26694    0.24572
     Net Profit Margin                             0.224142   0.212381
     Interest Coverage Ratio                      25.247222  21.386186
     Income Before Tax Profit Margin               0.274489   0.252666
     Effective Tax Rate                            0.183422   0.159438
     Return on Assets (ROA)                        0.162775    0.16323
     Return on Equity (ROE)                             NaN   0.559172
     Return on Invested Capital (ROIC)             0.269858   0.293721
     Return on Capital Employed (ROCE)             0.305968   0.297739
     Return on Tangible Assets                     0.555601   0.610645
     Income Quality Ratio                          1.300734   1.255809
     Net Income per EBT                            0.816578   0.840562
     Free Cash Flow to Operating Cash Flow Ratio   0.828073   0.848756
     EBT to EBIT Ratio                             0.957448   0.948408
     EBIT to Revenue                               0.286688    0.26641
MSFT Gross Margin                                  0.652474    0.65902
     Operating Margin                              0.317669    0.34137
     Net Profit Margin                             0.150154   0.311817
     Interest Coverage Ratio                      16.582144  20.342889
     Income Before Tax Profit Margin                 0.3305   0.347163
     Effective Tax Rate                            0.545676   0.101813
     Return on Assets (ROA)                        0.064018   0.136937
     Return on Equity (ROE)                             NaN   0.424106
     Return on Invested Capital (ROIC)             0.080826   0.263701
     Return on Capital Employed (ROCE)             0.195683   0.213571
     Return on Tangible Assets                     0.221938   0.414887
     Income Quality Ratio                          2.648241   1.329893
     Net Income per EBT                            0.454324   0.898187
     Free Cash Flow to Operating Cash Flow Ratio   0.734938   0.733161
     EBT to EBIT Ratio                             0.930293    0.94208
     EBIT to Revenue                               0.355265   0.368507

date                                                   2020       2021  \
AAPL Gross Margin                                  0.382332   0.417794
     Operating Margin                              0.241473   0.297824
     Net Profit Margin                             0.209136   0.258818
     Interest Coverage Ratio                      26.920989  45.456711
     Income Before Tax Profit Margin               0.244398   0.298529
     Effective Tax Rate                            0.144282   0.133023
     Return on Assets (ROA)                        0.177256   0.269742
     Return on Equity (ROE)                        0.736856   1.474433
     Return on Invested Capital (ROIC)             0.344126   0.503852
     Return on Capital Employed (ROCE)             0.320207   0.495972
     Return on Tangible Assets                     0.878664   1.500713
     Income Quality Ratio                          1.405201   1.098838
     Net Income per EBT                            0.855718   0.866977
     Free Cash Flow to Operating Cash Flow Ratio   0.909401   0.893452
     EBT to EBIT Ratio                             0.958936   0.976353
     EBIT to Revenue                               0.254864   0.305759
MSFT Gross Margin                                   0.67781   0.689258
     Operating Margin                              0.370304   0.415949
     Net Profit Margin                             0.309625   0.364517
     Interest Coverage Ratio                      25.378232  34.783461
     Income Before Tax Profit Margin               0.370842   0.423005
     Effective Tax Rate                            0.165077   0.138266
     Return on Assets (ROA)                        0.146961   0.183568
     Return on Equity (ROE)                        0.401398   0.470787
     Return on Invested Capital (ROIC)             0.262065    0.31958
     Return on Capital Employed (ROCE)             0.242912   0.299639
     Return on Tangible Assets                     0.397974   0.456606
     Income Quality Ratio                          1.370227   1.252469
     Net Income per EBT                            0.834923   0.861734
     Free Cash Flow to Operating Cash Flow Ratio   0.745513   0.731274
     EBT to EBIT Ratio                             0.953422   0.968059
     EBIT to Revenue                               0.388959   0.436962

date                                                   2022
AAPL Gross Margin                                  0.433096
     Operating Margin                              0.302887
     Net Profit Margin                             0.253096
     Interest Coverage Ratio                      44.538042
     Income Before Tax Profit Margin                0.30204
     Effective Tax Rate                            0.162045
     Return on Assets (ROA)                        0.282924
     Return on Equity (ROE)                        1.754593
     Return on Invested Capital (ROIC)             0.562645
     Return on Capital Employed (ROCE)             0.613937
     Return on Tangible Assets                     1.969589
     Income Quality Ratio                          1.223921
     Net Income per EBT                            0.837955
     Free Cash Flow to Operating Cash Flow Ratio   0.912338
     EBT to EBIT Ratio                             0.975982
     EBIT to Revenue                               0.309473
MSFT Gross Margin                                  0.684017
     Operating Margin                              0.420553
     Net Profit Margin                             0.366863
     Interest Coverage Ratio                      47.427533
     Income Before Tax Profit Margin               0.422232
     Effective Tax Rate                            0.131134
     Return on Assets (ROA)                         0.19937
     Return on Equity (ROE)                        0.471513
     Return on Invested Capital (ROIC)             0.346586
     Return on Capital Employed (ROCE)             0.317985
     Return on Tangible Assets                      0.46854
     Income Quality Ratio                          1.224051
     Net Income per EBT                            0.868866
     Free Cash Flow to Operating Cash Flow Ratio   0.731723
     EBT to EBIT Ratio                              0.97595
     EBIT to Revenue                               0.432637