In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
from pandas_datareader import data as pdr
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('fivethirtyeight')
plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus'] = False

In [3]:
stock_df = pd.read_csv('KOSPI200_data_202006-202206.csv', encoding='cp949')

In [4]:
stock_df

,일자,종가,대비,등락률,시가,고가,저가,거래량,거래대금,상장시가총액
0,2022/06/14,328.23,-1.65,-0.50,325.68,329.27,323.36,174251.0,7468386.0,1.712327e+09
1,2022/06/13,329.88,-12.01,-3.51,335.76,335.97,329.88,163806.0,7193816.0,1.719014e+09
2,2022/06/10,341.89,-4.73,-1.36,342.32,343.25,340.66,136208.0,6290154.0,1.781298e+09
3,2022/06/09,346.62,0.40,0.12,345.35,346.82,343.69,191392.0,8507880.0,1.788694e+09
4,2022/06/08,346.22,0.55,0.16,346.46,348.11,345.56,123302.0,6030966.0,1.787550e+09
...,...,...,...,...,...,...,...,...,...,...
489,2020/06/19,283.37,1.46,0.52,284.56,284.70,278.53,189129.0,7524815.0,1.254996e+09
490,2020/06/18,281.91,-1.11,-0.39,281.74,283.39,280.02,181587.0,7225991.0,1.250366e+09
491,2020/06/17,283.02,0.43,0.15,282.08,284.90,278.33,337225.0,11514655.0,1.256153e+09
492,2020/06/16,282.59,14.64,5.46,275.89,282.59,274.00,247894.0,9831669.0,1.254373e+09
493,2020/06/15,267.95,-13.83,-4.91,278.61,280.87,267.95,262445.0,12965653.0,1.190142e+09